# headline will be showed in index
headline: Hi, There!

# topbar menu link
menu:
  Archives: 
    link: /archives/
  Directory:
    link: /directory/

copyright:
  duration: 2019-2020
  license:
    title: Creative Commons Attribution-ShareAlike 4.0 International License
    link: https://creativecommons.org/licenses/by-sa/4.0/

historyHash: true

# katex (latex)
katex: true

# button fixed on the right bottom side
button:
  back2top: true # back to top
  darkmode: true # switch light/dark mode
  comment: true # go to valine comment

# if false, the index page will only show your first several articles 
# without paginator.
index_pagination: true

# generate a set of directory page under yoursite.com/directory/
directory:
  enable: true
  title: Directory
  parent_directory: Directory Above
  wordmap:
    home_page: 主页

# To be exact, it count the file's bytes.
wordcount: true

# valine comment
valine:
  enable: true
  appid:
  appkey:
  placeholder:
  notify: true
  visitor: true

jsonContent:
  meta: true
  drafts: false
  file: search.json
  keywords: undefined
  dateFormat: YYYY-MM-DD
  pages:
    title: true
    slug: false
    date: false
    updated: true
    comments: false
    path: true
    link: false
    permalink: false
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
    author: true
  posts:
    title: true
    slug: false
    date: false
    updated: true
    comments: false
    path: true
    link: false
    permalink: false
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
    author: true
    categories: true
    tags: true
